##### General #####
set -g base-index 1
set -g renumber-windows on
set-option -g set-titles on
set-option -g set-titles-string "#T - #W"
set -g mouse on
set -g history-limit 50000
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

##### Prefix #####
unbind C-b
set -g prefix C-a
bind C-a send-prefix

##### Activity #####
setw -g monitor-activity off
set -g visual-activity off

##### Splits & navigation #####
unbind =
bind = select-layout tiled
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -n M-Left select-pane -L
bind -n M-Down select-pane -D
bind -n M-Up select-pane -U
bind -n M-Right select-pane -R

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

##### Copy mode #####
unbind [
bind Escape copy-mode
unbind p
bind p paste-buffer

##### Status bar #####
warn='colour1'
muted='colour245'
bgactive='colour250'
fgactive='colour0'

set -g status-justify left
set -g status-position bottom
set -g status-style bg=default
set -g status-left ''
set -g status-left-length 100
set -g status-right '#{prefix_highlight} %H:%M '
set -g status-right-length 100
set -g status-right-style bg=$bgactive,fg=$fgactive,bold
set -g message-style bg=$bgactive,fg=$fgactive,bold

setw -g window-status-format ' #I#{?#{window_zoomed_flag},+, }│ #W '
setw -g window-status-style bg=default,bold,fg=$muted
setw -g window-status-current-format ' ✦ #I#{?#{window_zoomed_flag},+, }│ #W '
setw -g window-status-current-style bg=$bgactive,fg=$fgactive,bold
setw -g window-status-bell-style bg=$warn,fg=default,bold

set -g pane-border-style bg=default,fg=$muted
set -g pane-active-border-style bg=default,fg=$bgactive

##### TPM #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set -g @prefix_highlight_fg $fgactive
set -g @prefix_highlight_bg $bgactive
set -g @prefix_highlight_prefix_prompt '✦'

run "$HOME/.config/tmux/plugins/tpm/tpm"
